<?php if(!$_SESSION['is_admin']){ header('location:?p=404'); }?>
<?php $list = $usr->listUser(); ?>
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
     <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Ajouter un utilisateur</h1>
     </div>
     <h3 class="text-center mb-5">Formulaire d'ajout</h3>

     <form action=""class="col-5 m-auto">
        <div class="form-group message"></div>
        <div class="form-group mb-3">
            <label for="inputEmail" class="visually-hidden">email</label>
            <input type="text" id="inputEmail" class="form-control require" placeholder="email">
        </div>

        <div class="form-group">
            <button onclick="return false" class="w-100 btn btn-lg btn-success" id="submitCreate" type="submit">Créer</button>
        </div>
    </form>
  </form>
</main>